menu:
  items:
    - {
      "label": "Portfolio",
      "link": ":portfolio_index_path"
    }
    - {
      "label": "About Me",
      "link": ":show_page_path about-me"
    }
    - {
      "label": "Contact Me",
      "link": ":show_page_path contact-me",
      "turbolinks": false
    }
